# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(max_length=30)),
                ('Maker', models.CharField(max_length=10)),
                ('Year', models.IntegerField()),
                ('Size', models.CharField(max_length=10)),
                ('Fuel', models.CharField(max_length=10)),
                ('Accident', models.CharField(max_length=10)),
                ('Shift', models.CharField(max_length=10)),
                ('Color', models.CharField(max_length=10)),
                ('Distance', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CarData',
        ),
    ]
