# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0003_car_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='published_date',
        ),
    ]
